version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    # Roda a aplicação Flask

  tests:
    build: .
    command: pytest
    depends_on:
      - app
    # Roda os testes automatizados (requer que a app esteja no ar)