name: Docker Compose CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install legacy docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
              
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
        # ou use a instalação manual acima
      
      - name: Build and test
        run: |
          docker-compose --version
          docker-compose up -d app
          docker-compose run tests