name: Docker Compose CI


on: [push]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker/setup-buildx-action@v2
          docker-compose --version

      - name: Build and run tests
        run: |
          docker-compose up -d app  # Sobe a aplicação em background
          docker-compose run tests   # Executa os testes
          docker-compose down        # Remove os containers após os testes

      - name: Verify app is running
        run: |
          curl -X POST http://localhost:5000/validate-cpf \
               -H "Content-Type: application/json" \
               -d '{"cpf":"52998224725"}' | grep '"valid":true'