name: Docker Compose CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-qemu-action@v2
        uses: docker/setup-buildx-action@v2
      
      - name: Run with Docker Compose
        run: |
          # Usando a sintaxe nativa do Docker Compose V2
          docker compose version  # Novo formato (sem hífen)
          docker compose up -d app
          docker compose run tests
          docker compose down